import "./globals.css";
import { Inter } from "next/font/google";
import AppBar from "@/components/ui/layout/AppBar";
import CenteredLayout from "@/components/ui/layout/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen w-full flex flex-col">
          <AppBar
            avatarSrc={"https://ui-avatars.com/api/?name=John+Doe"}
            isLogoText={true}
            logoText={"OpenCourse"}
            items={[
              {
                title: "Home",
                link: "/",
              },
              { title: "FAQ", link: "/faq" },
              { title: "Register", link: "/register" },
              { title: "Login", link: "/login" },
            ]}
            logoAlt={"logo"}
            badgeText={"32"}
          />
          {children}
        </div>
      </body>
    </html>
  );
}
